import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as cp from 'child_process';
import { TASS_PATH, TASS_EXISTS, TABLES_MATCH_TASS } from '../helpers/compiler';
import { addressingModesFor } from '../../src/server/addressing';
import { opcodesForCpu } from '../../src/server/constants';

/**
 * The addressing table in `addressing.ts` is generated by probing the assembler.
 * This re-runs that probe and compares, so a wrong or stale table cannot ship -
 * and if 64tass itself changes, the failure says exactly which forms moved.
 *
 * Three representative targets rather than all eleven: the base NMOS set, the
 * CMOS additions, and the 16-bit set that has the most distinct forms.
 */
const PROBED_CPUS = ['6502', '65c02', '65816'];

const SYNTAXES = [
    '', 'a', '*+2', '#$12', '$34', '$34,x', '$34,y', '$1234', '$1234,x', '$1234,y',
    '$123456', '$123456,x', '($1234)', '($34,x)', '($34),y', '($34),z', '($34)',
    '($1234,x)', '[$34]', '[$34],y', '$12,s', '($12,s),y', '$12,$34', '0,$12', '0,$12,*+3',
];

interface Probe { pattern: string; opcode: number; length: number; }

function probe(cpu: string, mnemonic: string, dir: string): Probe[] {
    const file = path.join(dir, 'p.asm');
    const flag = `--m${cpu}`;
    const header = ['        * = $1000', '        .as', '        .xs'];
    const run = (syntaxes: string[], listTo?: string) => {
        fs.writeFileSync(file, header.concat(syntaxes.map(s => `        ${mnemonic} ${s}`)).join('\n') + '\n');
        const list = listTo ? `-L ${listTo}` : '';
        try {
            return cp.execSync(`${TASS_PATH} --quiet ${flag} -o /dev/null ${list} ${file} 2>&1`, { encoding: 'utf-8' });
        } catch (e) {
            const err = e as { stdout?: string; stderr?: string };
            return String(err.stdout ?? '') + String(err.stderr ?? '');
        }
    };

    // Pass 1: any error suppresses the listing, so first find which forms are rejected.
    const bad = new Set<number>();
    for (const line of run(SYNTAXES).split('\n')) {
        const m = line.match(/p\.asm:(\d+):\d+: error:/);
        if (m) bad.add(parseInt(m[1], 10));
    }
    const ok = SYNTAXES.filter((_, i) => !bad.has(i + 4));
    if (ok.length === 0) return [];

    // Pass 2: assemble only the accepted forms and read the bytes off the listing.
    const listFile = path.join(dir, 'list.txt');
    run(ok, listFile);
    let listing: string;
    try { listing = fs.readFileSync(listFile, 'utf-8'); } catch { return []; }

    const found: Probe[] = [];
    const seen = new Set<number>();
    for (const line of listing.split('\n')) {
        if (!line.startsWith('.')) continue;
        const parts = line.split('\t').filter(s => s.length > 0);
        if (parts.length < 3) continue;
        const bytes = parts[1].trim().split(/\s+/);
        if (!/^[0-9a-f]{2}$/.test(bytes[0])) continue;
        // The monitor column is the assembler's own disassembly of what it encoded.
        const mm = parts[2].trim().match(/^([a-z0-9]+)\s*(.*)$/i);
        // A different mnemonic means the operand was a register (`ldx a` is TAX);
        // those are register modes, tracked separately.
        if (!mm || mm[1].toLowerCase() !== mnemonic) continue;

        const operand = mm[2].trim();
        const addr = operand.match(/\$([0-9a-f]{4})/i);
        const encoded = bytes.slice(1).reverse().join('');
        const isRelative = !!addr && bytes.length >= 2 && encoded.toLowerCase() !== addr[1].toLowerCase();
        let pattern = operand
            .replace(/\$[0-9a-f]{6}/gi, '$hhhhhh')
            .replace(/\$[0-9a-f]{4}/gi, isRelative ? '<label>' : '$hhhh')
            .replace(/\$[0-9a-f]{2}/gi, '$hh')
            .replace(/^0,/, '<bit>,');
        if (pattern === '#') pattern = '';   // 64tass renders a bare BRK as "brk #"

        const opcode = parseInt(bytes[0], 16);
        if (seen.has(opcode)) continue;
        seen.add(opcode);
        found.push({ pattern, opcode, length: bytes.length });
    }
    return found.sort((a, b) => a.opcode - b.opcode);
}

describe.skipIf(!TASS_EXISTS || !TABLES_MATCH_TASS)('addressing modes match the assembler', () => {
    it.each(PROBED_CPUS)('%s', (cpu) => {
        const dir = fs.mkdtempSync(path.join(os.tmpdir(), '64tass-addr-'));
        try {
            const mismatches: string[] = [];
            for (const mnemonic of [...opcodesForCpu(cpu)].sort()) {
                const expected = probe(cpu, mnemonic, dir);
                const actual = addressingModesFor(cpu, mnemonic)
                    .map(([pattern, opcode, length]) => ({ pattern, opcode, length }));
                if (JSON.stringify(actual) !== JSON.stringify(expected)) {
                    mismatches.push(`${mnemonic}: table ${JSON.stringify(actual)} vs assembler ${JSON.stringify(expected)}`);
                }
            }
            expect(mismatches).toEqual([]);
        } finally {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    }, 120000);
});

describe('addressing table spot checks', () => {
    // Well-known encodings, so a corrupted table fails even without an assembler.
    it.each([
        ['6502', 'lda', '#$hh', 0xa9, 2],
        ['6502', 'lda', '$hh', 0xa5, 2],
        ['6502', 'lda', '$hhhh,x', 0xbd, 3],
        ['6502', 'jmp', '$hhhh', 0x4c, 3],
        ['6502', 'jmp', '($hhhh)', 0x6c, 3],
        ['6502', 'bne', '<label>', 0xd0, 2],
        ['6502', 'rts', '', 0x60, 1],
        ['65816', 'lda', '$hhhhhh', 0xaf, 4],
        ['65816', 'jml', '$hhhhhh', 0x5c, 4],
        ['65c02', 'lda', '($hh)', 0xb2, 2],
    ])('%s %s %s', (cpu, mnemonic, pattern, opcode, length) => {
        const mode = addressingModesFor(cpu, mnemonic).find(m => m[0] === pattern);
        expect(mode, `${cpu} ${mnemonic} ${pattern}`).toBeDefined();
        expect(mode![1]).toBe(opcode);
        expect(mode![2]).toBe(length);
    });

    it('does not give a 6502 the 65816-only long forms', () => {
        expect(addressingModesFor('6502', 'lda').map(m => m[0])).not.toContain('$hhhhhh');
    });

    it('has no modes for a mnemonic the CPU lacks', () => {
        expect(addressingModesFor('6502', 'bra')).toEqual([]);
        expect(addressingModesFor('6502', 'nonsense')).toEqual([]);
    });
});
